app:
  title: "AI Fabric Recommender"
  subtitle: "Dissertation Project — University of West London"
  theme_color: "#1F4E79"
  brand_logo: "assets/logo.png"

model:
  n_estimators: 200
  random_state: 42
  test_size: 0.25

features:
  moisture_regain: ["moisture", "regain"]
  water_absorption: ["water", "absorption"]
  drying_time: ["drying", "time"]
  thermal_conductivity: ["thermal", "conductivity"]

target_keywords: ["comfort", "score"]
